# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Object Detector' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Object Detector

  pod 'SnapKit', '~> 5.0.0'
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'
  pod 'RxSwiftExt', '~> 6'
  pod 'GoogleMLKit/ObjectDetection', '2.3.0'
end
